# Generated by Django 2.0.5 on 2019-02-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shirts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/image/')),
            ],
        ),
    ]
