# Generated by Django 2.0.5 on 2019-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0003_auto_20190216_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/shirt/'),
        ),
    ]
