# Generated by Django 2.0.5 on 2019-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0004_auto_20190216_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(upload_to='shirts/'),
        ),
    ]
