# Generated by Django 2.0.5 on 2019-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirt', '0008_auto_20190226_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='Shirt'),
        ),
    ]
