# Generated by Django 2.0.5 on 2019-03-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('customar_name', models.CharField(max_length=100)),
                ('customar_mail', models.CharField(max_length=100)),
                ('customar_phone', models.CharField(max_length=30)),
                ('customar_Parmanent_address', models.CharField(max_length=200)),
                ('customar_present_address', models.CharField(max_length=200)),
                ('customar_city', models.CharField(max_length=300)),
            ],
        ),
    ]
