# Generated by Django 2.0.5 on 2019-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pant',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='Pant'),
        ),
    ]
